# Generated by Django 4.0.6 on 2022-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
